project:
  type: website
  output-dir: docs

website:
  title: "jaredbpetry.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Quicksand
    css: styles.css
    toc: true
    

editor: visual

