project:
  type: website
  output-dir: docs

website:
  title: "Jared Petry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd
        text: Posts
      - href: Resume/Resume.pdf
        text: Resume

format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Quicksand
    css: styles.css
    toc: true
    

editor: visual

